const data = [
    'name 1',
    'name 2',
    'name 3',
    'name 4',
    'name 14',
    'name 1ge',
    'name 1dss',
    'name 1ds',
    'name 1',
    'name 2',
    'name 3',
    'name 4',
    'name 14',
    'name 1ge',
    'name 1dss',
    'name 1ds',
    'name 1',
    'name 2',
    'name 3',
    'name 4',
    'name 14',
    'name 1ge',
    'name 1dss',
    'name 1ds',
    'name 1',
    'name 2',
    'name 3',
    'name 4',
    'name 14',
    'name 1ge',
    'name 1dss',
    'name 1ds',
];

export default data; 